version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ringside_db
    environment:
      POSTGRES_DB: ringside
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  ai_api:
    build: ./ai-service
    container_name: ringside_api
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data: